### PR TITLE
Custom button

### PR DESCRIPTION
**Pull request by deji2ghost**

### CODE REVIEW

**Review by iamBlissMedik — CHANGES_REQUESTED** [review]
- The customButton should have a width,what if you want it to be longer,and also the loader??? are you saying clicking on the button,the text shouyld disappear,then the loader should show?? what about making the loader appear beside the text?

**Comment by deji2ghost** [comment]
I've already fixed it on the new pR> - The customButton should have a width,what if you want it to be longer,and also the loader??? are you saying clicking on the button,the text shouyld disappear,then the loader should show?? what about making the loader appear beside the text?

**Comment by iamBlissMedik** [comment]
> Merge

yes

**Comment by deji2ghost** [comment]
Make I merge this PR Abi? Or the new PR?

**Comment by iamBlissMedik** [comment]
ok

**Pull request merged**
